title: "MetaShot documentation"
#description: "A Jekyll theme for documentation"
#footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

#baseurl: ""
#url: "https://metashot.github.io"


remote_theme: pmarsceill/just-the-docs

aux_links:
    "MetaShot on GitHub":
      - "//github.com/metashot"

color_scheme: "light"
search_enabled: true
