title: "MetaShot documentation"
description: "A curated set of analysis pipelines for metagenomics and bacterial genomics"
footer_content: "Copyright &copy; 2020 MetaShot developers"

#baseurl: ""
#url: "https://metashot.github.io"


remote_theme: pmarsceill/just-the-docs@v0.3.3

aux_links:
    "MetaShot on GitHub":
      - "//github.com/metashot"

color_scheme: "metashot"
search_enabled: true
