# Setup
title:               MetaShot
tagline:             'A curated set of analysis pipelines for metagenomics and bacterial genomics'
description:         ''
url:                 'https://metashot.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              MetaShot developers
  url:               'metashot.github.io'
  email:             davide.albanese@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
